"""
Build mature_senpai_commercial_v26 from the accepted v17 runtime asset.

v26 keeps the v17/v25 face, hair, outfit, facial morphs, QA clips, and
secondary bones, but focuses on the safest visible runtime improvement:

- overly simple v25 cylindrical arms and paper-thin hands

The pass stays procedural because it is intended for repeatable web-preview
assets generated by remote Blender headless. It is not a substitute for a final
artist-sculpted quad mesh, but it gives the runtime a cleaner split/body layer
for movement QA.
"""

from __future__ import annotations

import importlib.util
import json
import math
from pathlib import Path
from typing import Any

import bpy


PROJECT_ROOT = Path(globals().get("PROJECT_ROOT", "/home/dennisj/apps/magic-academy-rpg-preview"))
TOOLS_DIR = PROJECT_ROOT / "assets/characters/mature_senpai/tools"

spec = importlib.util.spec_from_file_location("build_final_v25", TOOLS_DIR / "build_final_v25.py")
if spec is None or spec.loader is None:
    raise RuntimeError("Unable to load build_final_v25.py")
v25 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(v25)

SOURCE_GLB = PROJECT_ROOT / "public/assets/models/mature_senpai_commercial_v17.glb"
OUTPUT_GLB = PROJECT_ROOT / "public/assets/models/mature_senpai_commercial_v26.glb"
OUTPUT_PNG = PROJECT_ROOT / "public/assets/models/mature_senpai_commercial_v26.png"
OUTPUT_BLEND = PROJECT_ROOT / "assets/characters/mature_senpai/source/mature_senpai_commercial_v26.blend"
OUTPUT_REPORT = PROJECT_ROOT / "assets/characters/mature_senpai/mature_senpai_commercial_v26.report.json"

v25.SOURCE_GLB = SOURCE_GLB
v25.OUTPUT_GLB = OUTPUT_GLB
v25.OUTPUT_PNG = OUTPUT_PNG
v25.OUTPUT_BLEND = OUTPUT_BLEND
v25.OUTPUT_REPORT = OUTPUT_REPORT
v25.v17.OUTPUT_GLB = OUTPUT_GLB
v25.v17.OUTPUT_PNG = OUTPUT_PNG
v25.v17.OUTPUT_BLEND = OUTPUT_BLEND
v25.v17.OUTPUT_REPORT = OUTPUT_REPORT
v25.v17.v12.OUTPUT_GLB = OUTPUT_GLB
v25.v17.v12.OUTPUT_PNG = OUTPUT_PNG
v25.v17.v12.OUTPUT_BLEND = OUTPUT_BLEND
v25.v17.v12.OUTPUT_REPORT = OUTPUT_REPORT

MORPH_NAMES = ["Blink", "ConfidentSmile", "WarmSmile", "Teasing", "Surprised", "Thoughtful"]
ENABLE_TORSO_ARTIFACT_CLEANUP = False
ENABLE_SHOULDER_TRANSITION_CAP = False


def clean_scene() -> None:
    v25.clean_scene()


def make_material(name: str, color: tuple[float, float, float, float], roughness: float) -> bpy.types.Material:
    return v25.make_material(name, color, roughness)


def normalize_weights(weights: dict[str, float]) -> dict[str, float]:
    return v25.normalize_weights(weights)


def list_morph_targets(obj: bpy.types.Object | None) -> list[str]:
    return v25.list_morph_targets(obj)


def torso_width_limit(z: float) -> float:
    if z >= 1.46:
        return 0.170
    if z >= 1.34:
        return 0.180
    if z >= 1.22:
        return 0.200
    return 0.260


def clean_torso_camisole_artifacts(obj: bpy.types.Object) -> dict[str, Any]:
    """Delete old Hunyuan arm/sleeve islands that were misclassified as torso."""
    mesh = obj.data
    marked_faces: list[int] = []
    for polygon in mesh.polygons:
        center = polygon.center
        if center.z < 1.12 or center.z > 1.58:
            continue
        center_outside = abs(center.x) > torso_width_limit(center.z)
        outside_vertices = 0
        for vertex_index in polygon.vertices:
            vertex = mesh.vertices[vertex_index]
            if abs(vertex.co.x) > torso_width_limit(vertex.co.z):
                outside_vertices += 1
        if center_outside or outside_vertices >= 1:
            marked_faces.append(polygon.index)

    if not marked_faces:
        return {"removedFaces": 0, "removedLooseVertices": 0}

    bpy.ops.object.mode_set(mode="OBJECT")
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.select_mode(type="FACE")
    bpy.ops.mesh.select_all(action="DESELECT")
    bpy.ops.object.mode_set(mode="OBJECT")
    for polygon in mesh.polygons:
        polygon.select = polygon.index in marked_faces
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.select_mode(type="FACE")
    bpy.ops.mesh.delete(type="FACE")
    bpy.ops.object.mode_set(mode="OBJECT")
    mesh.update(calc_edges=True)
    obj["commercial_v26_torso_cleanup"] = "removed old arm/sleeve artifact faces from inherited Torso_Camisole split"
    return {"removedFaces": len(marked_faces), "removedLooseVertices": 0}


def import_clean_v17_source() -> tuple[list[bpy.types.Object], bpy.types.Object, list[dict[str, Any]], dict[str, Any]]:
    meshes, armature, replaced_source_parts = v25.import_v17_source()
    armature.name = "MatureSenpai_V26_ProductionArmature"
    armature.data.name = "MatureSenpai_V26_ProductionArmatureData"

    cleanup_report: dict[str, Any] = {}
    for obj in meshes:
        obj.name = obj.name.replace("MatureSenpai_V25_", "MatureSenpai_V26_")
        obj.data.name = obj.data.name.replace("MatureSenpai_V25_", "MatureSenpai_V26_")
        obj["commercial_v26_source"] = "mature_senpai_commercial_v17"
        for modifier in obj.modifiers:
            if modifier.type == "ARMATURE":
                modifier.object = armature
        if "Torso_Camisole" in obj.name:
            if ENABLE_TORSO_ARTIFACT_CLEANUP:
                cleanup_report[obj.name] = clean_torso_camisole_artifacts(obj)
            else:
                cleanup_report[obj.name] = {
                    "skipped": True,
                    "reason": "source torso preserved for stable preview; destructive arm/sleeve cleanup exposed shoulder seam artifacts",
                    "removedFaces": 0,
                    "removedLooseVertices": 0,
                }
    return meshes, armature, replaced_source_parts, cleanup_report


def add_v26_anime_arm_hand_meshes(armature: bpy.types.Object) -> list[bpy.types.Object]:
    skin = make_material("CommercialV26_NaturalAnimeSkin_ArmsHands", (0.965, 0.805, 0.735, 1.0), 0.55)
    blush = make_material("CommercialV26_ElbowPalmSoftShade", (0.90, 0.60, 0.58, 1.0), 0.70)
    nail = make_material("CommercialV26_SoftNails", (0.995, 0.875, 0.845, 1.0), 0.50)
    created: list[bpy.types.Object] = []

    def build_side(side_name: str, sign: float) -> bpy.types.Object:
        vertices: list[tuple[float, float, float]] = []
        faces: list[list[int]] = []
        material_indices: list[int] = []
        vertex_weights: list[dict[str, float]] = []
        ring_segments = 22
        digit_segments = 10
        upper = f"{side_name}UpperArm"
        lower = f"{side_name}LowerArm"
        hand = f"{side_name}Hand"

        def add_face(face: list[int], material_index: int = 0) -> None:
            faces.append(face)
            material_indices.append(material_index)

        def append_vertex(point: tuple[float, float, float], weights: dict[str, float]) -> int:
            vertices.append(point)
            vertex_weights.append(weights)
            return len(vertices) - 1

        def add_ring(
            center: tuple[float, float, float],
            radius_x: float,
            radius_y: float,
            weights: dict[str, float],
            count: int = ring_segments,
            twist: float = 0.0,
        ) -> list[int]:
            indices: list[int] = []
            for segment in range(count):
                angle = math.tau * segment / count + twist
                indices.append(append_vertex(
                    (
                        center[0] + math.cos(angle) * radius_x,
                        center[1] + math.sin(angle) * radius_y,
                        center[2],
                    ),
                    weights,
                ))
            return indices

        def bridge(a: list[int], b: list[int], material_index: int = 0) -> None:
            count = min(len(a), len(b))
            for segment in range(count):
                add_face([a[segment], a[(segment + 1) % count], b[(segment + 1) % count], b[segment]], material_index)

        def add_shoulder_transition_cap() -> None:
            lat_count = 7
            lon_count = 16
            grid: list[list[int]] = []
            center = (sign * 0.190, -0.060, 1.420)
            scale = (0.026, 0.024, 0.070)
            for lat_index in range(lat_count + 1):
                v = lat_index / lat_count
                phi = -math.pi * 0.5 + math.pi * v
                row: list[int] = []
                for lon_index in range(lon_count):
                    u = lon_index / lon_count
                    theta = math.tau * u
                    x = center[0] + math.cos(phi) * math.cos(theta) * scale[0]
                    y = center[1] + math.cos(phi) * math.sin(theta) * scale[1]
                    z = center[2] + math.sin(phi) * scale[2]
                    chest = max(0.12, min(0.42, (z - 1.32) / 0.45))
                    row.append(append_vertex((x, y, z), {"Chest": chest, upper: 1.0 - chest}))
                grid.append(row)
            for lat_index in range(lat_count):
                bridge(grid[lat_index], grid[lat_index + 1])

        rings = [
            add_ring((sign * 0.196, -0.055, 1.452), 0.014, 0.011, {"Chest": 0.30, upper: 0.70}),
            add_ring((sign * 0.204, -0.055, 1.428), 0.025, 0.019, {"Chest": 0.22, upper: 0.78}, twist=0.08),
            add_ring((sign * 0.223, -0.058, 1.334), 0.027, 0.020, {upper: 0.90, lower: 0.10}, twist=0.04),
            add_ring((sign * 0.240, -0.062, 1.244), 0.025, 0.018, {upper: 0.44, lower: 0.56}),
            add_ring((sign * 0.244, -0.067, 1.166), 0.022, 0.016, {upper: 0.16, lower: 0.84}, twist=0.08),
            add_ring((sign * 0.236, -0.074, 1.090), 0.020, 0.014, {lower: 0.86, hand: 0.14}),
            add_ring((sign * 0.224, -0.082, 1.030), 0.016, 0.011, {lower: 0.28, hand: 0.72}, twist=0.06),
            add_ring((sign * 0.216, -0.090, 0.994), 0.020, 0.010, {hand: 1.0}),
        ]
        if ENABLE_SHOULDER_TRANSITION_CAP:
            add_shoulder_transition_cap()
        for current, nxt in zip(rings, rings[1:]):
            bridge(current, nxt)

        # Subtle elbow/palm shade patches give the mesh visible anatomical cues
        # without requiring a texture repaint in this procedural pass.
        for ring in (rings[3], rings[4]):
            back_indices = ring[2:6]
            if len(back_indices) >= 4:
                add_face(back_indices[:4], 1)

        palm_mid = add_ring((sign * 0.214, -0.095, 0.972), 0.024, 0.010, {hand: 1.0}, count=ring_segments, twist=0.04)
        palm_low = add_ring((sign * 0.213, -0.098, 0.948), 0.020, 0.008, {hand: 1.0}, count=ring_segments)
        bridge(rings[-1], palm_mid)
        bridge(palm_mid, palm_low)
        palm_center = append_vertex((sign * 0.213, -0.100, 0.944), {hand: 1.0})
        for segment in range(ring_segments):
            add_face([palm_low[(segment + 1) % ring_segments], palm_low[segment], palm_center])

        def add_small_quad(points: list[tuple[float, float, float]], material_index: int) -> None:
            base = len(vertices)
            for point in points:
                append_vertex(point, {hand: 1.0})
            add_face([base, base + 1, base + 2, base + 3], material_index)

        def add_digit_ring(
            center: tuple[float, float, float],
            radius_x: float,
            radius_y: float,
            count: int = digit_segments,
        ) -> list[int]:
            indices: list[int] = []
            for segment in range(count):
                angle = math.tau * segment / count
                indices.append(append_vertex(
                    (
                        center[0] + math.cos(angle) * radius_x,
                        center[1] + math.sin(angle) * radius_y,
                        center[2],
                    ),
                    {hand: 1.0},
                ))
            return indices

        def add_segmented_finger(
            base_x: float,
            base_y: float,
            base_z: float,
            length: float,
            radius_x: float,
            radius_y: float,
            splay: float,
        ) -> None:
            previous: list[int] | None = None
            samples = [0.0, 0.20, 0.44, 0.70, 0.92, 1.0]
            for t in samples:
                taper = 1.0 - 0.30 * t
                curve = math.sin(t * math.pi) * 0.0016
                ring = add_digit_ring(
                    (
                        base_x + sign * splay * t + sign * curve,
                        base_y - 0.0025 * t,
                        base_z - length * t,
                    ),
                    radius_x * taper,
                    radius_y * taper,
                )
                if previous is not None:
                    bridge(previous, ring)
                previous = ring
            if previous is None:
                return
            tip = append_vertex((base_x + sign * splay + sign * 0.0007, base_y - 0.0026, base_z - length - 0.0008), {hand: 1.0})
            for segment in range(digit_segments):
                add_face([previous[(segment + 1) % digit_segments], previous[segment], tip])

            nail_z0 = base_z - length * 0.83
            nail_z1 = base_z - length * 0.985
            nail_x = base_x + sign * splay * 0.94
            nail_y = base_y - radius_y * 1.18 - 0.002
            nail_half = radius_x * 0.70
            add_small_quad(
                [
                    (nail_x - nail_half, nail_y, nail_z0),
                    (nail_x + nail_half, nail_y, nail_z0),
                    (nail_x + nail_half * 0.72, nail_y - 0.0008, nail_z1),
                    (nail_x - nail_half * 0.72, nail_y - 0.0008, nail_z1),
                ],
                2,
            )
            for crease_t in (0.32, 0.62):
                crease_z = base_z - length * crease_t
                crease_x = base_x + sign * splay * crease_t
                crease_y = base_y - radius_y * 1.20 - 0.0015
                add_small_quad(
                    [
                        (crease_x - radius_x * 0.72, crease_y, crease_z + 0.0009),
                        (crease_x + radius_x * 0.72, crease_y, crease_z + 0.0009),
                        (crease_x + radius_x * 0.54, crease_y - 0.0004, crease_z - 0.0009),
                        (crease_x - radius_x * 0.54, crease_y - 0.0004, crease_z - 0.0009),
                    ],
                    1,
                )

        def add_segmented_thumb(base_x: float, base_y: float, base_z: float) -> None:
            previous: list[int] | None = None
            length = 0.034
            for t in [0.0, 0.28, 0.58, 0.84, 1.0]:
                taper = 1.0 - 0.25 * t
                ring = add_digit_ring(
                    (
                        base_x + sign * length * 0.48 * t,
                        base_y - 0.003 * t,
                        base_z - length * 0.74 * t,
                    ),
                    0.0044 * taper,
                    0.0032 * taper,
                )
                if previous is not None:
                    bridge(previous, ring)
                previous = ring
            if previous is None:
                return
            tip = append_vertex((base_x + sign * length * 0.50, base_y - 0.0034, base_z - length * 0.76), {hand: 1.0})
            for segment in range(digit_segments):
                add_face([previous[(segment + 1) % digit_segments], previous[segment], tip])

        for finger_offset, length, width, splay in [
            (-0.0135, 0.030, 0.0036, -0.0007),
            (-0.0045, 0.036, 0.0040, -0.0002),
            (0.0045, 0.034, 0.0038, 0.0002),
            (0.0135, 0.028, 0.0034, 0.0007),
        ]:
            add_segmented_finger(sign * (0.213 + finger_offset), -0.101, 0.946, length, width, width * 0.72, splay)
        add_segmented_thumb(sign * 0.236, -0.094, 0.968)

        mesh = bpy.data.meshes.new(f"MatureSenpai_V26_Arms_Hands_{side_name}Mesh")
        mesh.from_pydata(vertices, [], faces)
        mesh.update(calc_edges=True)
        mesh.materials.append(skin)
        mesh.materials.append(blush)
        mesh.materials.append(nail)
        for index, polygon in enumerate(mesh.polygons):
            polygon.material_index = material_indices[index] if index < len(material_indices) else 0
            polygon.use_smooth = True

        obj = bpy.data.objects.new(f"MatureSenpai_V26_Arms_Hands_{side_name}", mesh)
        bpy.context.collection.objects.link(obj)
        obj.parent = armature
        obj.matrix_parent_inverse = armature.matrix_world.inverted()
        armature_modifier = obj.modifiers.new("V26 clean anatomical armature", "ARMATURE")
        armature_modifier.object = armature
        for vertex_index, weights in enumerate(vertex_weights):
            for bone_name, weight in normalize_weights(weights).items():
                group = obj.vertex_groups.get(bone_name) or obj.vertex_groups.new(name=bone_name)
                group.add([vertex_index], weight, "ADD")
        obj["commercial_v26_geometry_cleanup"] = "higher-density procedural anime arm/hand with corrected positive-X Left binding"
        return obj

    created.append(build_side("Left", 1.0))
    created.append(build_side("Right", -1.0))
    return created


def summarize_binding(meshes: list[bpy.types.Object], armature: bpy.types.Object) -> dict[str, Any]:
    return v25.summarize_binding(meshes, armature)


def summarize_parts(meshes: list[bpy.types.Object]) -> list[dict[str, Any]]:
    return v25.summarize_parts(meshes)


def write_report(
    meshes: list[bpy.types.Object],
    armature: bpy.types.Object,
    replaced_source_parts: list[dict[str, Any]],
    cleanup_report: dict[str, Any],
    authored_arm_parts: list[bpy.types.Object],
) -> None:
    face = next((obj for obj in meshes if "Face_Head" in obj.name), None)
    face_morphs = list_morph_targets(face)
    morph_meshes = [obj.name for obj in meshes if list_morph_targets(obj)]
    part_names = [obj.name for obj in meshes]
    total_faces = sum(len(obj.data.polygons) for obj in meshes)
    binding = summarize_binding(meshes, armature)
    secondary = v25.v17.v12.summarize_secondary_bones(armature)
    animations = [action.name for action in bpy.data.actions]
    torso_removed_faces = sum(item.get("removedFaces", 0) for item in cleanup_report.values())
    torso_preserved = any(item.get("skipped") for item in cleanup_report.values())
    acceptance_checks = {
        "keepsV17VisualCore": all(
            any(part in name for name in part_names)
            for part in ["Face_Head", "Hair_Back", "Hair_LeftLock", "Hair_RightLock", "Torso_Camisole", "Skirt_Center", "Legs", "Shoes"]
        ),
        "preservesSourceTorsoAfterCleanupRegression": torso_preserved and torso_removed_faces == 0,
        "replacesFragmentedSourceArms": bool(replaced_source_parts)
        and not any(name == "MatureSenpai_V26_Arms_Hands" for name in part_names),
        "hasHigherDensityAnatomicalArmHands": len(authored_arm_parts) == 2
        and all(len(obj.data.polygons) >= 400 for obj in authored_arm_parts),
        "keepsFaceOnlyExpressionMorphs": face is not None and morph_meshes == [face.name] and sorted(face_morphs) == sorted(MORPH_NAMES),
        "keepsHairSecondaryBones": len(secondary["hair"]) >= 6,
        "keepsSkirtSecondaryBones": len(secondary["skirt"]) >= 5,
        "keepsDeformationQaClips": any(name.startswith("v17_deformation_stress") for name in animations)
        and any(name.startswith("v17_secondary_sway_test") for name in animations),
        "hasWeightedRuntimeMeshes": binding["zeroWeightVertices"] == 0,
        "webRuntimeBudgetTarget": total_faces <= 65000,
    }
    report = {
        "assetId": "mature-senpai-commercial-v26",
        "characterId": "mature_senpai",
        "status": "stable-source-torso-and-anatomical-hands-preview",
        "source": "public/assets/models/mature_senpai_commercial_v17.glb",
        "blendSource": "assets/characters/mature_senpai/source/mature_senpai_commercial_v26.blend",
        "output": "public/assets/models/mature_senpai_commercial_v26.glb",
        "thumbnail": "public/assets/models/mature_senpai_commercial_v26.png",
        "generatedBy": "remote Blender headless + assets/characters/mature_senpai/tools/build_final_v26.py",
        "runtime": {
            "defaultAsset": True,
            "format": "glb",
            "url": "/assets/models/mature_senpai_commercial_v26.glb",
            "thumbnailUrl": "/assets/models/mature_senpai_commercial_v26.png",
            "fallbackAssetId": "mature-senpai-commercial-v17",
            "threeRuntimeFeatures": [
                "v17 face, hair, skirt, legs, shoes, choker, expression layer, and QA clips",
                "source Torso_Camisole preservation after destructive cleanup exposed shoulder seam artifacts",
                "higher-density procedural anime arms and segmented hands",
                "dedicated Face_Head morphTargetInfluences",
                "Secondary_* bone spring overlay",
            ],
        },
        "productionFlags": {
            "physicalRuntimeSplitParts": True,
            "dedicatedFaceExpressionMorphs": True,
            "sourcePreservedV17VisualCore": True,
            "sourceTorsoPreservedForStablePreview": torso_preserved,
            "legacyTorsoArmSleeveFragmentsRemoved": False,
            "fragmentedSourceArmsRemoved": True,
            "higherDensityAnatomicalHands": True,
            "hairSecondaryBones": True,
            "skirtSecondaryBones": True,
            "webRuntimeReady": True,
        },
        "runtimeParts": summarize_parts(meshes),
        "replacedSourceParts": replaced_source_parts,
        "torsoCleanup": cleanup_report,
        "authoredArmHandParts": [obj.name for obj in authored_arm_parts],
        "morphTargets": {face.name: face_morphs} if face else {},
        "armatureBones": [bone.name for bone in armature.data.bones],
        "secondaryRig": secondary,
        "binding": binding,
        "animationClips": animations,
        "acceptanceChecks": acceptance_checks,
        "runtimeDecision": {
            "defaultAsset": True,
            "fallbackAssetId": "mature-senpai-commercial-v17",
            "reason": "v26 is the current stable preview default: it keeps the visually stable v17 source torso after destructive torso cleanup exposed shoulder seams, while replacing the fragmented source arms with higher-density procedural anime arms/hands. v17 remains the deformation-production fallback.",
        },
        "limitations": [
            "v26 still uses a procedural arm/hand reconstruction rather than a sculptor-authored full quad retopology.",
            "The inherited source torso still contains some sleeve/arm artifact texture islands; a destructive automated cleanup was rejected because it exposed worse shoulder seams.",
            "The replacement arms use procedural materials and will need UV/texture repaint to perfectly match the Hunyuan atlas.",
            "Skirt panel texture islands remain source-preserved; final commercial polish still needs an artist cloth-retopo and brush-painted secondary weights.",
        ],
    }
    OUTPUT_REPORT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_REPORT.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main() -> dict[str, Any]:
    clean_scene()
    meshes, armature, replaced_source_parts, cleanup_report = import_clean_v17_source()
    authored_arm_parts = add_v26_anime_arm_hand_meshes(armature)
    meshes.extend(authored_arm_parts)
    face = next((obj for obj in meshes if "Face_Head" in obj.name), meshes[0])
    v25.v17.v12.render_preview(face, meshes)
    v25.v17.export_outputs(meshes, armature)
    write_report(meshes, armature, replaced_source_parts, cleanup_report, authored_arm_parts)
    return {
        "glb": str(OUTPUT_GLB),
        "png": str(OUTPUT_PNG),
        "blend": str(OUTPUT_BLEND),
        "report": str(OUTPUT_REPORT),
        "runtimeParts": len(meshes),
        "torsoCleanup": cleanup_report,
        "authoredArmHandParts": [obj.name for obj in authored_arm_parts],
    }


if __name__ == "__main__":
    print(json.dumps(main(), indent=2))
