import type { CharacterId, CharacterSpec } from './CharacterSpec';
import { storyNpcCharacterSpecs } from './StoryNpcCharacterSpecs';

export const playerSpec: CharacterSpec = {
  id: 'player',
  displayName: 'Academy Protagonist',
  designIntent:
    'A young male magic academy student with a clean Japanese RPG hero silhouette, readable from the third-person camera and detailed enough for dialogue close-ups.',
  body: {
    heightMeters: 1.68,
    headToBodyRatio: 0.18,
    silhouette: 'slim-male-academy',
    shoulderWidth: 0.43,
    torsoLength: 0.54,
    waistWidth: 0.31,
    hipWidth: 0.34,
    armLength: 0.61,
    handScale: 0.96,
    legLength: 0.83,
    footScale: 1,
  },
  face: {
    eyeShape: 'large almond anime eyes',
    eyeColor: '#355c9a',
    eyeScale: 1.08,
    browShape: 'soft confident arc',
    browColor: '#2d1f18',
    noseBridge: 'stylized-minimal',
    mouthShape: 'small neutral heroic',
    cheekTint: '#f0b8aa',
    expressionSet: ['neutral', 'smile', 'surprised', 'focused', 'embarrassed'],
  },
  hair: {
    color: '#2a1d17',
    highlightColor: '#6d4a32',
    style: 'layered short academy cut',
    bangs: 'asymmetric side-swept bangs',
    length: 'short',
    volume: 0.74,
    secondaryMotion: 'tips',
    accessories: [],
  },
  outfit: {
    style: 'formal magic academy uniform',
    primaryColor: '#132b68',
    secondaryColor: '#f6f0dc',
    accentColor: '#d7b45f',
    torso: 'tailored navy jacket with fitted cream shirt',
    sleeves: 'structured sleeves with gold cuff trim',
    lowerBody: 'slim dark academy trousers',
    outerwear: 'short navy mage cape with gold border',
    shoes: 'polished dark ankle boots',
    accessories: ['academy crest brooch', 'belt pouch'],
    heldItems: ['practice wand'],
  },
  animation: {
    locomotionSet: 'academy-male-locomotion',
    idleSet: 'reserved-student-idles',
    interactionSet: 'conversation-male-calm',
    facialSet: 'anime-hero-basic',
    secondaryMotion: ['cape-sway', 'hair-tip-sway'],
  },
  runtime: {
    role: 'hero',
    preferredAssetId: 'player-hero-v1',
    fallbackRigId: 'player-procedural-rig',
    lodProfile: 'hero-near',
    maxVisibleDistanceMeters: 48,
  },
};

export const lyraSpec: CharacterSpec = {
  id: 'lyra',
  displayName: 'Lyra',
  designIntent:
    'A charming magic academy heroine with a soft Japanese RPG visual-novel portrait match, petite proportions, expressive face, and natural idle motion.',
  body: {
    heightMeters: 1.55,
    headToBodyRatio: 0.22,
    silhouette: 'petite-heroine',
    shoulderWidth: 0.33,
    torsoLength: 0.47,
    waistWidth: 0.24,
    hipWidth: 0.35,
    armLength: 0.54,
    handScale: 0.9,
    legLength: 0.74,
    footScale: 0.88,
  },
  face: {
    eyeShape: 'large rounded sparkling anime eyes',
    eyeColor: '#7b66ff',
    eyeScale: 1.18,
    browShape: 'gentle curved brow',
    browColor: '#8a6cff',
    noseBridge: 'stylized-minimal',
    mouthShape: 'small soft smile',
    cheekTint: '#f4a8c4',
    expressionSet: ['neutral', 'warm-smile', 'curious', 'shy', 'delighted', 'thinking'],
  },
  hair: {
    color: '#b69cff',
    highlightColor: '#f0dcff',
    style: 'long layered lavender hair',
    bangs: 'soft center bangs with side locks',
    length: 'long',
    volume: 0.88,
    secondaryMotion: 'full',
    accessories: ['small star hair clip', 'ribbon tie'],
  },
  outfit: {
    style: 'romantic magic academy uniform',
    primaryColor: '#f8f2ff',
    secondaryColor: '#7d56d9',
    accentColor: '#f0c86e',
    torso: 'fitted white blouse with purple ribbon',
    sleeves: 'soft short sleeves with pale trim',
    lowerBody: 'layered purple academy skirt',
    outerwear: 'short pale capelet with star lining',
    shoes: 'cream ankle boots with purple details',
    accessories: ['star pendant', 'spellbook satchel'],
    heldItems: ['small spellbook'],
  },
  animation: {
    locomotionSet: 'academy-female-locomotion',
    idleSet: 'gentle-heroine-idles',
    interactionSet: 'conversation-female-warm',
    facialSet: 'anime-heroine-basic',
    secondaryMotion: ['long-hair-sway', 'skirt-sway', 'capelet-sway', 'ribbon-sway'],
  },
  runtime: {
    role: 'hero',
    preferredAssetId: 'lyra-hero-v1',
    fallbackRigId: 'lyra-procedural-rig',
    lodProfile: 'hero-near',
    maxVisibleDistanceMeters: 42,
  },
};

export const miraVossSpec: CharacterSpec = {
  id: 'mira_voss',
  displayName: 'Mira Voss',
  designIntent:
    'A mirror astrologer heroine for the academy story roster, with silver-blue hair, cool aqua eyes, reflective uniform details, and a reserved but expressive conversation pose.',
  body: {
    heightMeters: 1.62,
    headToBodyRatio: 0.2,
    silhouette: 'petite-heroine',
    shoulderWidth: 0.34,
    torsoLength: 0.49,
    waistWidth: 0.25,
    hipWidth: 0.34,
    armLength: 0.56,
    handScale: 0.9,
    legLength: 0.77,
    footScale: 0.9,
  },
  face: {
    eyeShape: 'large reflective aqua anime eyes',
    eyeColor: '#7dd9f4',
    eyeScale: 1.13,
    browShape: 'calm worried arc',
    browColor: '#6f96bd',
    noseBridge: 'stylized-minimal',
    mouthShape: 'small reserved smile',
    cheekTint: '#d7a9be',
    expressionSet: ['neutral', 'blink', 'smile', 'concerned', 'surprised'],
  },
  hair: {
    color: '#9fc8df',
    highlightColor: '#e5f8ff',
    style: 'long silver-blue astrologer hair',
    bangs: 'side-swept fringe with glossy face locks',
    length: 'long',
    volume: 0.9,
    secondaryMotion: 'full',
    accessories: ['mirror shard hairpin'],
  },
  outfit: {
    style: 'blue-white mirror astrologer academy uniform',
    primaryColor: '#eef9ff',
    secondaryColor: '#3f74b8',
    accentColor: '#6fc8f1',
    torso: 'white fitted blouse with blue astrologer panels',
    sleeves: 'soft academy sleeves with reflective cuff trim',
    lowerBody: 'layered blue academy skirt with star chart sash',
    outerwear: 'short reflective capelet with mirror shard accents',
    shoes: 'white ankle boots with silver-blue trim',
    accessories: ['academy crest brooch', 'mirror shard hairpin', 'star chart sash'],
    heldItems: ['mirror star compass'],
  },
  animation: {
    locomotionSet: 'academy-female-locomotion',
    idleSet: 'reserved-astrologer-idles',
    interactionSet: 'conversation-female-thoughtful',
    facialSet: 'anime-heroine-reflective',
    secondaryMotion: ['long-hair-sway', 'capelet-sway', 'sash-sway'],
  },
  runtime: {
    role: 'supporting',
    preferredAssetId: 'mira-voss-supporting-v1',
    fallbackRigId: 'mira-voss-procedural-rig',
    lodProfile: 'supporting-mid',
    maxVisibleDistanceMeters: 36,
  },
};

export const matureSenpaiSpec: CharacterSpec = {
  id: 'mature_senpai',
  displayName: 'Elena',
  designIntent:
    'A mature big-sister academy NPC based on the v7 Hunyuan/illustration reference: burgundy long hair, elegant ivory camisole top, lavender double side-slit skirt, and Roman-style strappy high heels. Runtime uses the commercial v12 source-preserving asset because it keeps the natural mcp-polish-v2 likeness while adding semantic part groups, six facial morph targets, supplemental hair/skirt secondary weights, and visible strap/choker/pendant detail parts; mcp-polish-v2 remains the visual fallback and commercial v11 remains the split-part engineering reference.',
  body: {
    heightMeters: 1.72,
    headToBodyRatio: 0.18,
    silhouette: 'teacher',
    shoulderWidth: 0.37,
    torsoLength: 0.52,
    waistWidth: 0.28,
    hipWidth: 0.39,
    armLength: 0.59,
    handScale: 0.94,
    legLength: 0.86,
    footScale: 0.94,
  },
  face: {
    eyeShape: 'soft mature purple anime eyes',
    eyeColor: '#7b55b6',
    eyeScale: 1.08,
    browShape: 'gentle confident arc',
    browColor: '#6b243f',
    noseBridge: 'stylized-minimal',
    mouthShape: 'small elegant smile',
    cheekTint: '#e7b4aa',
    expressionSet: ['neutral', 'blink', 'confident-smile', 'teasing', 'surprised', 'thoughtful'],
  },
  hair: {
    color: '#6b243f',
    highlightColor: '#b74d70',
    style: 'long wavy burgundy hair',
    bangs: 'side-parted bangs with layered face locks',
    length: 'long',
    volume: 0.9,
    secondaryMotion: 'full',
    accessories: [],
  },
  outfit: {
    style: 'elegant mature academy fantasy outfit',
    primaryColor: '#f6f0e6',
    secondaryColor: '#a999d8',
    accentColor: '#d5aa4f',
    torso: 'ivory fitted camisole-style top with thin gold straps',
    sleeves: 'sleeveless thin straps',
    lowerBody: 'lavender high-waist skirt with double side slits',
    outerwear: 'none',
    shoes: 'ivory and gold Roman-style strappy high-heeled sandals',
    accessories: ['gold choker with purple gem pendant', 'gold star skirt accents'],
    heldItems: [],
  },
  animation: {
    locomotionSet: 'academy-female-locomotion',
    idleSet: 'mature-senpai-rigged-preview',
    interactionSet: 'conversation-female-confident',
    facialSet: 'anime-mature-basic',
    secondaryMotion: ['long-hair-sway', 'skirt-sway', 'strap-sway', 'pendant-sway'],
  },
  runtime: {
    role: 'supporting',
    preferredAssetId: 'mature-senpai-commercial-v15',
    fallbackRigId: 'mature-senpai-procedural-rig',
    lodProfile: 'supporting-mid',
    maxVisibleDistanceMeters: 30,
  },
};

export const characterSpecs: Record<string, CharacterSpec> = {
  player: playerSpec,
  lyra: lyraSpec,
  mira_voss: miraVossSpec,
  mature_senpai: matureSenpaiSpec,
  ...storyNpcCharacterSpecs,
};

export function hasCharacterSpec(id: CharacterId): boolean {
  return characterSpecs[id] !== undefined;
}

export function getCharacterSpec(id: CharacterId): CharacterSpec {
  const spec = characterSpecs[id];
  if (!spec) throw new Error(`Unknown character spec: ${id}`);
  return spec;
}
